### ISSUE TITLE
I ran :BadApple 8 times, now I have 8 Bad Apples playing simultaneously, help

### ISSUE THREAD

**Issue by kuator** [seandewar/bad-apple.nvim#1]
Yeah

**Comment by kuator** [comment]
Nevermind, they finished playing

**Comment by seandewar** [comment]
Thank you for bringing this issue to my attention!

After much investigation, it appears that quitting Neovim fixes this issue.
However, it is a known fact that quitting (Neo)vim is an extremely hard task that even the [world's best Vim speed-runners struggle with](https://www.youtube.com/watch?v=TLbfqZBL8t8).

Therefore, I believe the simplest way to fix this issue is to install the (award-winning, ultra minimal and blazingly fast) [`sigsegvim` Neovim framework](https://github.com/seandewar/sigsegvim) and run the `:Sigsegvim` command.

Alternatively, if you have `libcanberra` installed, be sure to crank that volume slider to 11 and launch 8 more `:BadApple`s to drown out the music from the first 8.

I hope this helps and I'm sorry for any inconvenience caused. :heart:
